// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/marcopolo.proto

package marcopolo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Ip                   string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Src                  string            `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Lat                  float32           `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float32           `protobuf:"fixed32,4,opt,name=long,proto3" json:"long,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            int64             `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_500a03696185e060, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Message) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Message) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Message) GetLong() float32 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Message) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Burp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Burp) Reset()         { *m = Burp{} }
func (m *Burp) String() string { return proto.CompactTextString(m) }
func (*Burp) ProtoMessage()    {}
func (*Burp) Descriptor() ([]byte, []int) {
	return fileDescriptor_500a03696185e060, []int{1}
}

func (m *Burp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Burp.Unmarshal(m, b)
}
func (m *Burp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Burp.Marshal(b, m, deterministic)
}
func (m *Burp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Burp.Merge(m, src)
}
func (m *Burp) XXX_Size() int {
	return xxx_messageInfo_Burp.Size(m)
}
func (m *Burp) XXX_DiscardUnknown() {
	xxx_messageInfo_Burp.DiscardUnknown(m)
}

var xxx_messageInfo_Burp proto.InternalMessageInfo

func (m *Burp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Burp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterMapType((map[string]string)(nil), "Message.TagsEntry")
	proto.RegisterType((*Burp)(nil), "Burp")
}

func init() { proto.RegisterFile("proto/marcopolo.proto", fileDescriptor_500a03696185e060) }

var fileDescriptor_500a03696185e060 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0xbf, 0xf4, 0xef, 0xd7, 0x2b, 0xc8, 0x70, 0x51, 0x09, 0xc3, 0x2c, 0x4a, 0x17, 0xd2,
	0x55, 0x95, 0x71, 0xe1, 0xe0, 0x52, 0x71, 0x39, 0x20, 0xd5, 0x17, 0x88, 0x25, 0x94, 0x62, 0xd2,
	0x84, 0x24, 0x1d, 0x98, 0xb7, 0xf4, 0x91, 0x24, 0x99, 0x8c, 0xee, 0xce, 0xf9, 0x85, 0x93, 0x7b,
	0xee, 0x85, 0x6b, 0x6d, 0x94, 0x53, 0x77, 0x92, 0x99, 0x41, 0x69, 0x25, 0x54, 0x17, 0x7c, 0xf3,
	0x4d, 0xa0, 0xdc, 0x73, 0x6b, 0xd9, 0xc8, 0xf1, 0x12, 0x92, 0x49, 0x53, 0x52, 0x93, 0xb6, 0xea,
	0x93, 0x49, 0xe3, 0x0a, 0x52, 0x6b, 0x06, 0x9a, 0x04, 0xe0, 0xa5, 0x27, 0x82, 0x39, 0x9a, 0xd6,
	0xa4, 0x4d, 0x7a, 0x2f, 0x11, 0x21, 0x13, 0x6a, 0x1e, 0x69, 0x16, 0x50, 0xd0, 0x78, 0x0b, 0x99,
	0x63, 0xa3, 0xa5, 0x79, 0x9d, 0xb6, 0x17, 0x5b, 0xec, 0xe2, 0xff, 0xdd, 0x07, 0x1b, 0xed, 0xeb,
	0xec, 0xcc, 0xb1, 0x0f, 0xef, 0xb8, 0x81, 0xca, 0x4d, 0x92, 0x5b, 0xc7, 0xa4, 0xa6, 0x45, 0x4d,
	0xda, 0xb4, 0xff, 0x03, 0xeb, 0x47, 0xa8, 0x7e, 0x03, 0x7e, 0xf0, 0x17, 0x3f, 0xc6, 0x6e, 0x5e,
	0xe2, 0x15, 0xe4, 0x07, 0x26, 0x16, 0x1e, 0xeb, 0x9d, 0xcc, 0x53, 0xb2, 0x23, 0xcd, 0x0e, 0xb2,
	0xe7, 0xc5, 0x68, 0xbc, 0x81, 0xc2, 0x3a, 0xe6, 0x16, 0x1b, 0x62, 0x79, 0x1f, 0x1d, 0x52, 0x28,
	0xe5, 0xa9, 0x51, 0xcc, 0x9e, 0xed, 0xf6, 0x1e, 0x56, 0x7b, 0x7f, 0x9f, 0x37, 0x25, 0xd4, 0x3b,
	0x37, 0x87, 0x69, 0xe0, 0xb8, 0x81, 0xf2, 0x45, 0xcd, 0x76, 0x91, 0x1c, 0xff, 0x9f, 0x37, 0x59,
	0xe7, 0x9d, 0x9f, 0xd0, 0xfc, 0xfb, 0x2c, 0xc2, 0x15, 0x1f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xf8, 0xf8, 0x84, 0xe5, 0x5e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarcoPoloServiceClient is the client API for MarcoPoloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarcoPoloServiceClient interface {
	Consume(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Burp, error)
}

type marcoPoloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarcoPoloServiceClient(cc grpc.ClientConnInterface) MarcoPoloServiceClient {
	return &marcoPoloServiceClient{cc}
}

func (c *marcoPoloServiceClient) Consume(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Burp, error) {
	out := new(Burp)
	err := c.cc.Invoke(ctx, "/MarcoPoloService/Consume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarcoPoloServiceServer is the server API for MarcoPoloService service.
type MarcoPoloServiceServer interface {
	Consume(context.Context, *Message) (*Burp, error)
}

// UnimplementedMarcoPoloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMarcoPoloServiceServer struct {
}

func (*UnimplementedMarcoPoloServiceServer) Consume(ctx context.Context, req *Message) (*Burp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consume not implemented")
}

func RegisterMarcoPoloServiceServer(s *grpc.Server, srv MarcoPoloServiceServer) {
	s.RegisterService(&_MarcoPoloService_serviceDesc, srv)
}

func _MarcoPoloService_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarcoPoloServiceServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MarcoPoloService/Consume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarcoPoloServiceServer).Consume(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarcoPoloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MarcoPoloService",
	HandlerType: (*MarcoPoloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Consume",
			Handler:    _MarcoPoloService_Consume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/marcopolo.proto",
}
